name: Flutter CI/CD Pipeline

# ワークフローをトリガーするイベントを定義
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# ワークフロー内のジョブを定義
jobs:
  build:
    # ジョブが実行される仮想環境を指定
    runs-on: ubuntu-latest

    # ジョブ内のステップを定義
    steps:
      - name: Checkout repository
        # リポジトリをチェックアウトするアクションを使用
        uses: actions/checkout@v2

      - name: Set up Flutter
        # Flutterをセットアップするアクションを使用
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"

      - name: Install dependencies
        run: flutter pub get

      - name: Format
        run: dart format .

      - name: Analyze
        run: flutter analyze

      # - name: Build APK
      #   # リリース用のAPKをビルドするコマンドを実行
      #   run: flutter build apk --release
